<a href="https://colab.research.google.com/github/Ajaykrishnan11/churn-predictor-streamlit/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [52]:
from google.colab import files
uploaded = files.upload()


Saving Telco-Customer-Churn.csv to Telco-Customer-Churn (2).csv


In [53]:
import io
df = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))

In [54]:
df.head()


customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [55]:
print("Dataset shape:",df.shape)
print("\nColumn types:\n",df.dtypes)
print("nMissing values:\n",df.isnull().sum())


Dataset shape: (7043, 21)

Column types:
 customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object
nMissing values:
 customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract

In [56]:
print("\nChurn distribution:\n", df['Churn'].value_counts())


Churn distribution:
 Churn
No     5174
Yes    1869
Name: count, dtype: int64


In [57]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('Churn')

In [58]:
df_encoded = df.copy()

In [59]:
le = LabelEncoder()
df_encoded['Churn']= le.fit_transform(df['Churn'])

In [60]:
for col in categorical_cols:
    if df_encoded[col].nunique() == 2:
        df_encoded[col] = le.fit_transform(df_encoded[col])
    else:
        df_encoded = pd.get_dummies(df_encoded, columns=[col])

In [61]:
X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

In [62]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

In [64]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [65]:
y_pred = model.predict(X_test)

In [66]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7913413768630234

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.86      1035
           1       0.65      0.47      0.54       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.70      1409
weighted avg       0.78      0.79      0.78      1409


Confusion Matrix:
 [[939  96]
 [198 176]]


In [67]:
# Install XGBoost if not already installed
!pip install xgboost

# Import XGBoost and LogisticRegression
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression


In [68]:
# Define models
models = {
    "Random Forest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42)
}

# Train, predict, and evaluate each model
for name, model in models.items():
    print(f"\n🔹 Training {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n📈 Evaluation for {name}:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



🔹 Training Random Forest...

📈 Evaluation for Random Forest:
Accuracy: 0.7913413768630234
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.86      1035
           1       0.65      0.47      0.54       374

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.70      1409
weighted avg       0.78      0.79      0.78      1409

Confusion Matrix:
 [[939  96]
 [198 176]]

🔹 Training XGBoost...


/usr/local/lib/python3.11/dist-packages/xgboost/training.py:183: UserWarning: [15:13:10] WARNING: /workspace/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)



📈 Evaluation for XGBoost:
Accuracy: 0.7799858055358411
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.87      0.85      1035
           1       0.60      0.53      0.56       374

    accuracy                           0.78      1409
   macro avg       0.72      0.70      0.71      1409
weighted avg       0.77      0.78      0.78      1409

Confusion Matrix:
 [[901 134]
 [176 198]]

🔹 Training Logistic Regression...

📈 Evaluation for Logistic Regression:
Accuracy: 0.6493967352732435
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.57      0.71      1035
           1       0.42      0.86      0.57       374

    accuracy                           0.65      1409
   macro avg       0.67      0.72      0.64      1409
weighted avg       0.79      0.65      0.67      1409

Confusion Matrix:
 [[592 443]
 [ 51 323]]


In [69]:
# Summary table of accuracy scores
accuracy_scores = {}

for name, model in models.items():
    y_pred = model.predict(X_test)
    accuracy_scores[name] = accuracy_score(y_test, y_pred)

# Display accuracy comparison
print("\n✅ Model Accuracy Comparison:")
for name, score in accuracy_scores.items():
    print(f"{name}: {score:.4f}")



✅ Model Accuracy Comparison:
Random Forest: 0.7913
XGBoost: 0.7800
Logistic Regression: 0.6494


In [70]:
import joblib

# Find the best model
best_model_name = max(accuracy_scores, key=accuracy_scores.get)
best_model = models[best_model_name]

# Save the best model
joblib.dump(best_model, f"{best_model_name}_churn_model.pkl")
print(f"\n✅ Best model ({best_model_name}) saved as '{best_model_name}_churn_model.pkl'")



✅ Best model (Random Forest) saved as 'Random Forest_churn_model.pkl'


In [71]:
import numpy as np

# Get feature importances
if hasattr(best_model, "feature_importances_"):
    importances = best_model.feature_importances_
else:
    # fallback for logistic regression
    importances = np.abs(best_model.coef_[0])

# Top 10 feature names
top_10_idx = np.argsort(importances)[-10:]
top_10_features = X.columns[top_10_idx].tolist()

print("✅ Top 10 important features:\n", top_10_features)

# Save them for Streamlit app
joblib.dump(top_10_features, "top_10_features.pkl")


✅ Top 10 important features:
 ['TechSupport_Yes', 'PaperlessBilling', 'OnlineSecurity_No', 'Contract_Two year', 'PaymentMethod_Electronic check', 'InternetService_Fiber optic', 'TechSupport_No', 'Contract_Month-to-month', 'MonthlyCharges', 'tenure']


['top_10_features.pkl']

In [72]:
pip install streamlit

In [73]:
import streamlit as st
import joblib
import numpy as np

# Load saved files
model = joblib.load("Random Forest_churn_model.pkl")  # Corrected file name
scaler = joblib.load("scaler.pkl")
top_features = joblib.load("top_10_features.pkl")

st.set_page_config(page_title="Churn Predictor", page_icon="🔮")
st.title("🔮 Telco Customer Churn Predictor")

st.markdown("Provide values for the 10 most important customer features to predict churn:")

# Create input fields dynamically
user_inputs = []
feature_index_map = joblib.load("feature_columns.pkl") # Load the feature column names
for feature in top_features:
    if "Yes" in feature or "No" in feature:
        val = st.selectbox(f"{feature}", [0, 1])
    elif "InternetService" in feature:
        val = st.selectbox(f"{feature}", [0, 1])
    else:
        # Check if the feature is in the original dataframe columns and get its dtype
        original_dtype = df_encoded[feature_index_map].dtypes[feature]
        if original_dtype == 'int64':
            val = st.number_input(f"{feature}", value=0, format='%d') # Set format to integer if original type is int
        else:
            val = st.number_input(f"{feature}", value=0.0)
    user_inputs.append(val)

if st.button("Predict Churn"):
    input_array = np.zeros((1, scaler.mean_.shape[0]))  # Create an empty row with all features

    # Only update the selected top 10 features
    for idx, feature in enumerate(top_features):
        if feature in feature_index_map:
            feature_pos = feature_index_map.index(feature)
            input_array[0][feature_pos] = user_inputs[idx]
        else:
            # Handle one-hot encoded features - find the correct column in the input array
            # This part might need adjustment based on how one-hot encoding was applied
            # For simplicity, assuming the feature name directly corresponds to a column
             if feature in feature_index_map:
                feature_pos = feature_index_map.index(feature)
                input_array[0][feature_pos] = user_inputs[idx]


    # Scale input (match training scale)
    input_scaled = scaler.transform(input_array)

    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Prediction: Customer is likely to churn.")
    else:
        st.success("✅ Prediction: Customer is not likely to churn.")

2025-07-24 15:13:43.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-07-24 15:13:43.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

In [74]:
# Save the scaler
joblib.dump(scaler, "scaler.pkl")
print("✅ Scaler saved as 'scaler.pkl'")

# Save the feature column names
joblib.dump(X.columns.tolist(), "feature_columns.pkl")
print("✅ Feature column names saved as 'feature_columns.pkl'")

✅ Scaler saved as 'scaler.pkl'
✅ Feature column names saved as 'feature_columns.pkl'


In [75]:
app_code = '''
import streamlit as st
import joblib
import numpy as np

# Load saved files
model = joblib.load("Random Forest_churn_model.pkl")  # Replace with your best model file
scaler = joblib.load("scaler.pkl")
top_features = joblib.load("top_10_features.pkl")
all_features = joblib.load("feature_columns.pkl")

st.set_page_config(page_title="Churn Predictor", page_icon="🔮")
st.title("🔮 Telco Customer Churn Predictor")

st.markdown("Provide values for the 10 most important customer features to predict churn:")

# Input fields
user_inputs = []
for feature in top_features:
    if "Yes" in feature or "No" in feature:
        val = st.selectbox(f"{feature}", [0, 1])
    elif "InternetService" in feature:
        val = st.selectbox(f"{feature}", [0, 1])
    else:
        val = st.number_input(f"{feature}", value=0.0)
    user_inputs.append(val)

if st.button("Predict Churn"):
    input_array = np.array(user_inputs).reshape(1, -1)

    # Empty full input
    full_input = np.zeros((1, len(all_features)))

    # Fill top 10 values
    for idx, feature in enumerate(top_features):
        pos = all_features.index(feature)
        full_input[0][pos] = input_array[0][idx]

    # Scale
    full_input_scaled = scaler.transform(full_input)

    # Predict
    prediction = model.predict(full_input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Prediction: Customer is likely to churn.")
    else:
        st.success("✅ Prediction: Customer is not likely to churn.")
'''

with open("app.py", "w") as f:
    f.write(app_code)
print("✅ Streamlit app.py saved.")


✅ Streamlit app.py saved.


In [76]:
requirements = '''
streamlit
scikit-learn
xgboost
joblib
pandas
numpy
'''

with open("requirements.txt", "w") as f:
    f.write(requirements.strip())
print("✅ requirements.txt saved.")


✅ requirements.txt saved.


In [77]:
import zipfile

with zipfile.ZipFile("churn_predictor_app.zip", "w") as zipf:
    zipf.write("app.py")
    zipf.write("requirements.txt")
    zipf.write("Random Forest_churn_model.pkl")  # Corrected model file name
    zipf.write("scaler.pkl")
    zipf.write("feature_columns.pkl")
    zipf.write("top_10_features.pkl")

print("✅ Zipped all files into churn_predictor_app.zip")

✅ Zipped all files into churn_predictor_app.zip


In [78]:
from google.colab import files
files.download("churn_predictor_app.zip")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>